### PR TITLE
add shell command agent

### PR DESCRIPTION
**Pull request by narita1980**
This pull request introduces a new agent to GraphAI that enables the execution of external shell commands within data flows. This enhancement allows for more flexible and dynamic processing by integrating shell command execution directly into the workflow.

### CODE REVIEW

**Review by snakajima — APPROVED** [review]

**Comment by snakajima** [comment]
これを使うと、disk をformatする graph ファイルとか
作れちゃう点が、少し心配になります。

**Comment by snakajima** [comment]
This agent is too dangerous to add it as a vanilla agent.

**Comment by isamu** [comment]
Thank you for you PR.

The vanilla agent is a collection of agents that operate in both Node.js and the browser without relying on other npm packages. Adding this agent to the collection would not be appropriate.

Similar agents is here . Please see and use it.
https://www.npmjs.com/package/@graphai/shell_utilty_agent

**Comment by narita1980** [comment]
Thank you for reviewing and commenting on my PR. 

I appreciate your detailed feedback and for pointing out that the vanilla agent operates without relying on other npm packages.

Also, thank you for sharing the existing package on npm. 

I’ll review it and consider using it moving forward.

**Pull request closed without merging**
